import React from 'react';
import {GenericScrollBox} from '../main/GenericScrollBox';

export class Page extends React.Component {

  render() {
    return (
        <div>

          <GenericScrollBox ref="genericScrollBox" style={{border: 'solid 1px red', height: '400px', width: '400px'}} className="scroll-box--wrapped">
            <div className="scroll-box__viewport " style={{whiteSpace: 'nowrap'}}>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO <br/>
              FOOO
            </div>
          </GenericScrollBox>

          FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>FOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOOFOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>
          FOOO <br/>

        </div>
    )
  }
}
